# Generated by Django 3.1 on 2020-11-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NGOname', models.CharField(default='', max_length=200)),
                ('Location', models.TextField(default='')),
                ('PhoneNumber', models.IntegerField(default=0)),
                ('VerificationImage', models.ImageField(default='', upload_to='../media')),
                ('Cause', models.TextField(default='', max_length=200)),
            ],
        ),
    ]
