# Generated by Django 3.1 on 2020-11-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=200)),
                ('CommunityOrInstitution', models.CharField(default='', max_length=200)),
                ('Address', models.CharField(default='', max_length=5000)),
                ('PhoneNumber', models.IntegerField(default=0)),
                ('Age', models.IntegerField(default=0)),
                ('Gender', models.CharField(default='', max_length=200)),
                ('VerificationImage', models.ImageField(default='', upload_to='../media')),
                ('WhyDoYouWantToHelp', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='ngo',
            name='Cause',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='Location',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
