# Generated by Django 3.1 on 2020-11-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201121_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
    ]
