# Generated by Django 3.1 on 2020-11-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ngo_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='newNGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NGOname', models.CharField(default='', max_length=200)),
                ('Location', models.CharField(default='', max_length=5000)),
                ('PhoneNumber', models.IntegerField(default=0)),
                ('NgoLogo', models.ImageField(default='', upload_to='../media')),
                ('website', models.CharField(default='', max_length=200)),
                ('emailid', models.EmailField(default='xyz@xyz.com', max_length=254)),
                ('VerificationImage', models.ImageField(default='', upload_to='../media')),
                ('Cause', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
